version: 2.1

setup: true

orbs:
  codecov: codecov/codecov@5

jobs:
  go_test:
    docker:
      - image: cimg/go:1.24.1
    steps:
      - checkout
      - run:
          name: Run Go tests with coverage
          command: |
            mkdir -p coverage
            go test -coverprofile=coverage/coverage.txt ./...
            cat coverage/coverage.txt
      - codecov/upload:
          files: coverage/coverage.txt

workflows:
  setup:
    jobs:
      - go_test
