version: 2.1

orbs:
  codecov: codecov/codecov@5

parameters:
  run_go_test:
    type: boolean
    default: false

jobs:
  go_test:
    docker:
      - image: cimg/go:1.24.1
    steps:
      - checkout
      - run:
          name: Run Go tests with coverage
          command: |
            mkdir -p coverage
            go test -coverprofile=coverage/coverage.out ./...
      - codecov/upload:
          files: coverage/coverage.out

workflows:
  test:
    when: << pipeline.parameters.run_go_test >>
    jobs:
      - go_test
